### ISSUE TITLE
Please add the phone number

### ISSUE THREAD

**Issue by bolom** [LordAlexWorks/proactives#10]
https://www.evernote.com/shard/s96/sh/2664dd6c-3888-41e4-963d-fd683a8fc55b/8b6bb0faea1895057e6aba571d43ecea

**Comment by hassanakram** [comment]
Fixed

**Comment by bolom** [comment]
@kkannappan ready to QA

**Comment by kkannappan** [comment]
@bolom 

Tested in all major browsers, issue is not fixed. The Phone number is still not available in both language pages. Also, in French screen the site does not auto scroll to the form at the bottom of the page when user clicks on the 'Contact Us' button, it is currently happening in English page only.

![pro - phone number missing](https://cloud.githubusercontent.com/assets/2522583/5872948/f2f2a6ec-a316-11e4-8be4-546d369835e6.png)

**Comment by hassanakram** [comment]
@kkannappan Ready for QA.

**Comment by kkannappan** [comment]
@hassanakram 

Verified in all major browsers, issue is not fixed yet. The phone numbers are still not shown in the Contact Us section at the top right side, re-opening the issue.
