### ISSUE TITLE
add anchor for contact us

### ISSUE THREAD

**Issue by bolom** [LordAlexWorks/proactives#11]
https://www.evernote.com/shard/s96/sh/2664dd6c-3888-41e4-963d-fd683a8fc55b/8b6bb0faea1895057e6aba571d43ecea

**Comment by hassanakram** [comment]
Fixed

**Comment by bolom** [comment]
@kkannappan ready to QA

**Comment by kkannappan** [comment]
@bolom

Tested in all major browsers, issue is not fixed. In French screen the site does not auto scroll to the form at the bottom of the page when user clicks on the 'Contact Us' button, it is currently happening in English page only.

**Comment by hassanakram** [comment]
@kkannappan ready to QA.
