### ISSUE TITLE
Validate form fields

### ISSUE THREAD

**Issue by bolom** [LordAlexWorks/proactives#13]
Do not  submit if the form is not completed field.

**Comment by hassanakram** [comment]
Fixed

**Comment by bolom** [comment]
@kkannappan ready to QA

**Comment by kkannappan** [comment]
@bolom 

Tested in all major browsers, issue is partially fixed. Site does not submit the form if one field is empty in English language, however, it throws an error message 'We're sorry, but something went wrong.' when the form is submitted with an empty field in French language.

![pro - error when signup](https://cloud.githubusercontent.com/assets/2522583/5873614/55afdfa0-a31e-11e4-9b3f-c1eb1506fc70.png)

**Comment by hassanakram** [comment]
@kkannappan Ready for QA.

**Comment by kkannappan** [comment]
@hassanakram 

Verified in all major browsers, issue is fixed. Closing the issue.
